name: esg_codebase
channels:
  - defaults
dependencies:
  - wheel=0.36.2
  - openssl
  - python=3.8.10
  - pip=21.1.1
  - setuptools=52.0.0
  - certifi
  - ca-certificates
  - sqlite=3.35.4
  - black
  - pip:
    - altair==4.1.0
    - appnope==0.1.2
    - argon2-cffi==20.1.0
    - astor==0.8.1
    - astunparse==1.6.3
    - async-generator==1.10
    - backcall==0.2.0
    - base58==2.1.0
    - beautifulsoup4==4.9.3
    - bleach==3.3.0
    - blinker==1.4
    - cachetools==4.2.2
    - cffi==1.14.5
    - chardet==4.0.0
    - chart-studio==1.1.0
    - click==7.1.2
    - cloudpickle==1.6.0
    - colorama==0.4.4
    - croniter==0.3.37
    - dask==2021.6.0
    - decorator==5.0.9
    - defusedxml==0.7.1
    - distributed==2021.6.0
    - docker==5.0.0
    - entrypoints==0.3
    - fsspec==2021.5.0
    - future==0.18.2
    - gitdb==4.0.7
    - gitpython==3.1.17
    - heapdict==1.0.1
    - idna==2.10
    - imageio==2.9.0
    - install==1.3.4
    - ipykernel==5.5.5
    - ipython==7.23.1
    - ipython-genutils==0.2.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==3.0.1
    - joblib==1.0.1
    - jsonschema==3.2.0
    - jupyter-client==6.1.12
    - jupyter-core==4.7.1
    - jupyterlab-pygments==0.1.2
    - jupyterlab-widgets==1.0.0
    - livereload==2.6.3
    - locket==0.2.1
    - lunr==0.5.8
    - lxml==4.6.3
    - markdown==3.3.4
    - markupsafe==2.0.1
    - marshmallow==3.12.1
    - marshmallow-oneofschema==2.1.0
    - matplotlib-inline==0.1.2
    - mistune==0.8.4
    - mkdocs==1.1.2
    - mkdocs-autorefs==0.2.1
    - mkdocs-material==7.1.5
    - mkdocs-material-extensions==1.0.1
    - mkdocstrings==0.15.1
    - msgpack==1.0.2
    - natsort==7.1.1
    - nbclient==0.5.3
    - nbconvert==6.0.7
    - nbformat==5.1.3
    - nest-asyncio==1.5.1
    - nltk==3.6.2
    - notebook==6.4.0
    - numpy==1.20.3
    - packaging==20.9
    - pandas==1.2.4
    - pandocfilters==1.4.3
    - parso==0.8.2
    - partd==1.2.0
    - pendulum==2.1.2
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==8.2.0
    - plotly==4.14.3
    - prefect==0.14.21
    - prometheus-client==0.10.1
    - prompt-toolkit==3.0.18
    - protobuf==3.17.0
    - psutil==5.8.0
    - ptyprocess==0.7.0
    - pyarrow==4.0.0
    - pycparser==2.20
    - pydeck==0.6.2
    - pygments==2.9.0
    - pymdown-extensions==8.2
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - python-box==5.3.0
    - python-dateutil==2.8.1
    - python-slugify==5.0.2
    - pytickersymbols==1.7.0
    - pytkdocs==0.11.1
    - pytrends==4.7.3
    - pytz==2021.1
    - pytzdata==2020.1
    - pyyaml==5.4.1
    - pyzmq==22.0.3
    - requests==2.25.1
    - requests-futures==1.0.0
    - retrying==1.3.3
    - send2trash==1.5.0
    - six==1.16.0
    - smmap==4.0.0
    - sortedcontainers==2.4.0
    - soupsieve==2.2.1
    - streamlit==0.82.0
    - tabulate==0.8.9
    - tblib==1.7.0
    - terminado==0.10.0
    - testpath==0.5.0
    - text-unidecode==1.3
    - toolz==0.11.1
    - tornado==6.1
    - tqdm==4.60.0
    - traitlets==5.0.5
    - tzlocal==2.1
    - urllib3==1.26.4
    - validators==0.18.2
    - watchdog==2.1.2
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.0.1
    - widgetsnbextension==3.5.1
    - yahooquery==2.2.15
    - zict==2.0.0