site_name: ESG data codebase
repo_url: https://github.com/philippschmalen/ESG-data-codebase
repo_name: ESG-data-codebase
theme:
  name: material
  include_sidebar: true
site_dir: references/docs-site
plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          setup_commands:
            - import sys
            - sys.path.append("src/data/")
            # or sys.path.insert(0, "src")     
      watch:
        - src/data
nav:
  - Home: index.md
